# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Devals < Formula
  desc ""
  homepage ""
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/daido1976/devals/releases/download/v0.1.1/devals_Darwin_x86_64.tar.gz"
      sha256 "c1141dc0d6d113e74a8fe7b0d19a034c0a4e64a1996851a73a4088ba9de3bba9"

      def install
        bin.install "devals"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/daido1976/devals/releases/download/v0.1.1/devals_Darwin_arm64.tar.gz"
      sha256 "d3f64eed21558573dc13982c538451d1ba9e91c68dd3a1515f1a3a14309196e1"

      def install
        bin.install "devals"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/daido1976/devals/releases/download/v0.1.1/devals_Linux_arm64.tar.gz"
      sha256 "21d584c138fe29d4bda91d944da08e590b4a52e2fe45daee2a4476330d2a58d4"

      def install
        bin.install "devals"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/daido1976/devals/releases/download/v0.1.1/devals_Linux_x86_64.tar.gz"
      sha256 "ce03f82ea88560a764ad301af1163b88e56c53e4a655165976f80dc42cc10f4b"

      def install
        bin.install "devals"
      end
    end
  end
end
